language: python

matrix:
  include:

    - python: 3.5
    - python: 3.6

      dist: xenial
      sudo: true

virtualenv:
  system_site_packages: true

services:
  - docker

before_script: 
  - pip install docker-compose

script:
  - docker-compose run web python  userdomain/manage.py 
  - bash build.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag bmuserdjango_web  $DOCKER_USERNAME$/bmuserdjango_web
  - docker push $DOCKER_USERNAME$/bmuserdjango_web
  