language: python

python:
  - python: 3.7
    dist: xenial
    sudo: true


virtualenv:
  system_site_packages: true

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run web python  userdomain/manage.py