language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch

virtualenv:
  system_site_packages: true
  
services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run web python  userdomain/manage.py