language: python

matrix:
  include:

    - python: 3.5
    - python: 3.6

      dist: xenial
      sudo: true

virtualenv:
  system_site_packages: true

services:
  - docker

before_script: 
  - pip install docker-compose

script:
  - docker-compose run web python  userdomain/manage.py 
  - bash build.sh
  