language: python

matrix:
  include:
    - python: 3.5

virtualenv:
  system_site_packages: true

services:
  - docker

before_script: 
  - pip install docker-compose

script:
  - bash build.sh
  - bash docker_push

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t letzshake/bmuserdjango_web .  
  - docker run -d --name bmusers -t letzshake/bmuserdjango_web python ./userdomain/manage.py runserver 0.0.0.0:8000
  - sleep 15
  - docker run --name owasp --link bmusers -t owasp/zap2docker-weekly zap-full-scan.py -t http://bmusers:8000


  