language: python

python:
  - "3.5"


virtualenv:
  system_site_packages: true

services:
  - docker

before_script: pip3 install docker-compose

script:
  - docker-compose run web python  userdomain/manage.py