#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker pull $DOCKER_USERNAME/bmuserdjango_web
docker tag bmuserdjango_web $DOCKER_USERNAME/bmuserdjango_web
docker push $DOCKER_USERNAME/bmuserdjango_web